### ISSUE TITLE
I follow the quick start instructions. But fail to run inference.

### ISSUE THREAD

**Issue by viiika** [rese1f/aurora#4]
The log is attached 
```bash
(aurora) root@dsw-2470-69f5b95b9c-d78s8:/mnt/workspace/jinbin_output/caption_v2/aurora# python inference.py     --model_path wchai/AuroraCap-7B-VID-xtuner     --prompt "Describe the video in detail."     --visual_input assets/auroracap/test.mp4     --num_frm 8     --token_kept_ratio 0.8     --temperature 0.0     --top_p 1.0     --num_beams 1     --max_new_tokens 2048
/root/anaconda3/envs/aurora/lib/python3.10/site-packages/_distutils_hack/__init__.py:54: UserWarning: Reliance on distutils from stdlib is deprecated. Users must rely on setuptools to provide the distutils module. Avoid importing distutils or import setuptools first, and avoid setting SETUPTOOLS_USE_DISTUTILS=stdlib. Register concerns at https://github.com/pypa/setuptools/issues/new?template=distutils-deprecation.yml
  warnings.warn(
[2024-10-22 11:29:33,376] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/mnt/workspace/jinbin_output/caption_v2/aurora/inference.py", line 9, in <module>
    from src.xtuner.xtuner.model.aurora import AuroraEncoder, AuroraModel
  File "/mnt/workspace/jinbin_output/caption_v2/aurora/src/xtuner/xtuner/model/__init__.py", line 2, in <module>
    from .internvl import InternVL_V1_5
  File "/mnt/workspace/jinbin_output/caption_v2/aurora/src/xtuner/xtuner/model/internvl.py", line 8, in <module>
    from mmengine.model import BaseModel
  File "/root/anaconda3/envs/aurora/lib/python3.10/site-packages/mmengine/model/__init__.py", line 6, in <module>
    from .base_model import BaseDataPreprocessor, BaseModel, ImgDataPreprocessor
  File "/root/anaconda3/envs/aurora/lib/python3.10/site-packages/mmengine/model/base_model/__init__.py", line 2, in <module>
    from .base_model import BaseModel
  File "/root/anaconda3/envs/aurora/lib/python3.10/site-packages/mmengine/model/base_model/base_model.py", line 9, in <module>
    from mmengine.optim import OptimWrapper
  File "/root/anaconda3/envs/aurora/lib/python3.10/site-packages/mmengine/optim/__init__.py", line 2, in <module>
    from .optimizer import (OPTIM_WRAPPER_CONSTRUCTORS, OPTIMIZERS,
  File "/root/anaconda3/envs/aurora/lib/python3.10/site-packages/mmengine/optim/optimizer/__init__.py", line 5, in <module>
    from .builder import (OPTIM_WRAPPER_CONSTRUCTORS, OPTIMIZERS,
  File "/root/anaconda3/envs/aurora/lib/python3.10/site-packages/mmengine/optim/optimizer/builder.py", line 174, in <module>
    TRANSFORMERS_OPTIMIZERS = register_transformers_optimizers()
  File "/root/anaconda3/envs/aurora/lib/python3.10/site-packages/mmengine/optim/optimizer/builder.py", line 169, in register_transformers_optimizers
    OPTIMIZERS.register_module(name='Adafactor', module=Adafactor)
  File "/root/anaconda3/envs/aurora/lib/python3.10/site-packages/mmengine/registry/registry.py", line 661, in register_module
    self._register_module(module=module, module_name=name, force=force)
  File "/root/anaconda3/envs/aurora/lib/python3.10/site-packages/mmengine/registry/registry.py", line 611, in _register_module
    raise KeyError(f'{name} is already registered in {self.name} '
KeyError: 'Adafactor is already registered in optimizer at torch.optim'
```

My pip package version:
```bash
(aurora) root@dsw-2470-69f5b95b9c-d78s8:/mnt/workspace/jinbin_output/caption_v2/aurora# pip list
Package                       Version        Editable project location
----------------------------- -------------- ------------------------------------------------------------
accelerate                    1.0.1
addict                        2.4.0
aiohappyeyeballs              2.4.3
aiohttp                       3.10.10
aiosignal                     1.3.1
altair                        5.4.1
annotated-types               0.7.0
anyio                         4.6.2.post1
argon2-cffi                   23.1.0
argon2-cffi-bindings          21.2.0
arrow                         1.3.0
arxiv                         2.1.3
asttokens                     2.4.1
async-lru                     2.0.4
async-timeout                 4.0.3
attrs                         24.2.0
av                            13.1.0
babel                         2.16.0
beautifulsoup4                4.12.3
bitsandbytes                  0.44.1
black                         24.1.0
bleach                        6.1.0
blinker                       1.8.2
Brotli                        1.1.0
cachetools                    5.5.0
certifi                       2024.8.30
cffi                          1.17.1
cfgv                          3.4.0
chardet                       5.2.0
charset-normalizer            3.4.0
click                         8.1.7
colorama                      0.4.6
comm                          0.2.2
contourpy                     1.3.0
cycler                        0.12.1
DataProperty                  1.0.1
datasets                      2.16.1
debugpy                       1.8.7
decorator                     5.1.1
decord                        0.6.0
deepspeed                     0.15.2
defusedxml                    0.7.1
dill                          0.3.7
distlib                       0.3.9
distro                        1.9.0
docker-pycreds                0.4.0
duckduckgo_search             5.3.1b1
einops                        0.8.0
et-xmlfile                    1.1.0
evaluate                      0.4.3
exceptiongroup                1.2.2
executing                     2.1.0
fastjsonschema                2.20.0
feedparser                    6.0.11
filelock                      3.16.1
fonttools                     4.54.1
fqdn                          1.5.1
frozenlist                    1.4.1
fsspec                        2023.10.0
ftfy                          6.3.0
func_timeout                  4.3.5
gitdb                         4.0.11
GitPython                     3.1.43
griffe                        0.49.0
h11                           0.14.0
h2                            4.1.0
hf_transfer                   0.1.8
hjson                         3.1.0
hpack                         4.0.0
httpcore                      0.16.3
httpx                         0.23.3
huggingface-hub               0.26.1
hyperframe                    6.0.1
identify                      2.6.1
idna                          3.10
imageio                       2.36.0
importlib_metadata            8.5.0
ipykernel                     6.29.5
ipython                       8.28.0
ipywidgets                    8.1.5
isoduration                   20.11.0
isort                         5.13.2
jedi                          0.19.1
Jinja2                        3.1.4
jiter                         0.6.1
joblib                        1.4.2
json5                         0.9.25
jsonlines                     4.0.0
jsonpointer                   3.0.0
jsonschema                    4.23.0
jsonschema-specifications     2024.10.1
jupyter                       1.1.1
jupyter_client                8.6.3
jupyter-console               6.6.3
jupyter_core                  5.7.2
jupyter-events                0.10.0
jupyter-lsp                   2.2.5
jupyter_server                2.14.2
jupyter_server_terminals      0.5.3
jupyterlab                    4.2.5
jupyterlab_pygments           0.3.0
jupyterlab_server             2.27.3
jupyterlab_widgets            3.0.13
kiwisolver                    1.4.7
lagent                        0.2.4
lazy_loader                   0.4
lmms_eval                     0.2.3          /mnt/workspace/jinbin_output/caption_v2/aurora/src/lmms-eval
loguru                        0.7.2
lxml                          5.3.0
markdown-it-py                3.0.0
MarkupSafe                    3.0.2
matplotlib                    3.9.2
matplotlib-inline             0.1.7
mbstrdecoder                  1.1.3
mdurl                         0.1.2
mistune                       3.0.2
mmengine                      0.10.5
modelscope                    1.19.1
mpi4py_mpich                  3.1.5
mpmath                        1.3.0
msgpack                       1.1.0
multidict                     6.1.0
multiprocess                  0.70.15
mutagen                       1.47.0
mypy-extensions               1.0.0
narwhals                      1.10.0
nbclient                      0.10.0
nbconvert                     7.16.4
nbformat                      5.10.4
nest-asyncio                  1.6.0
networkx                      3.4.2
ninja                         1.11.1.1
nltk                          3.9.1
nodeenv                       1.9.1
notebook                      7.2.2
notebook_shim                 0.2.4
numexpr                       2.10.1
numpy                         1.26.4
nvidia-cublas-cu12            12.4.5.8
nvidia-cuda-cupti-cu12        12.4.127
nvidia-cuda-nvrtc-cu12        12.4.127
nvidia-cuda-runtime-cu12      12.4.127
nvidia-cudnn-cu12             9.1.0.70
nvidia-cufft-cu12             11.2.1.3
nvidia-curand-cu12            10.3.5.147
nvidia-cusolver-cu12          11.6.1.9
nvidia-cusparse-cu12          12.3.1.170
nvidia-ml-py                  12.560.30
nvidia-nccl-cu12              2.21.5
nvidia-nvjitlink-cu12         12.4.127
nvidia-nvtx-cu12              12.4.127
openai                        1.52.0
opencv-python                 4.10.0.84
opencv-python-headless        4.10.0.84
openpyxl                      3.1.5
overrides                     7.7.0
packaging                     24.1
pandas                        2.2.3
pandocfilters                 1.5.1
parso                         0.8.4
pathspec                      0.12.1
pathvalidate                  3.2.1
peft                          0.13.2
pexpect                       4.9.0
phx-class-registry            4.1.0
pillow                        10.4.0
pip                           24.2
platformdirs                  4.3.6
portalocker                   2.10.1
pre_commit                    4.0.1
prometheus_client             0.21.0
prompt_toolkit                3.0.48
propcache                     0.2.0
protobuf                      3.20.0
psutil                        6.1.0
ptyprocess                    0.7.0
pure_eval                     0.2.3
py-cpuinfo                    9.0.0
pyarrow                       17.0.0
pyarrow-hotfix                0.6
pybind11                      2.13.6
pycocoevalcap                 1.2
pycocotools                   2.0.8
pycparser                     2.22
pycryptodomex                 3.21.0
pydantic                      2.9.2
pydantic_core                 2.23.4
pydeck                        0.9.1
Pygments                      2.18.0
pyparsing                     3.2.0
pytablewriter                 1.2.0
python-dateutil               2.9.0.post0
python-json-logger            2.0.7
pytz                          2024.2
PyYAML                        6.0.2
pyzmq                         26.2.0
referencing                   0.35.1
regex                         2024.9.11
requests                      2.32.3
rfc3339-validator             0.1.4
rfc3986                       1.5.0
rfc3986-validator             0.1.1
rich                          13.9.2
rpds-py                       0.20.0
sacrebleu                     2.4.3
safetensors                   0.4.5
scikit-image                  0.24.0
scikit-learn                  1.5.2
scipy                         1.14.1
Send2Trash                    1.8.3
sentencepiece                 0.1.99
sentry-sdk                    2.17.0
setproctitle                  1.3.3
setuptools                    75.1.0
sgmllib3k                     1.0.0
six                           1.16.0
smmap                         5.0.1
sniffio                       1.3.1
socksio                       1.0.0
soupsieve                     2.6
sqlitedict                    2.1.0
stack-data                    0.6.3
streamlit                     1.39.0
sympy                         1.13.1
tabledata                     1.3.3
tabulate                      0.9.0
tcolorpy                      0.1.6
tenacity                      8.3.0
termcolor                     2.5.0
terminado                     0.18.1
threadpoolctl                 3.5.0
tifffile                      2024.9.20
tiktoken                      0.8.0
timeout-decorator             0.5.0
timm                          1.0.11
tinycss2                      1.3.0
tokenizers                    0.15.2
toml                          0.10.2
tomli                         2.0.2
torch                         2.5.0
torchvision                   0.20.0
tornado                       6.4.1
tqdm                          4.66.5
tqdm-multiprocess             0.0.11
traitlets                     5.14.3
transformers                  4.39.2
transformers-stream-generator 0.0.5
triton                        3.1.0
typepy                        1.3.2
types-python-dateutil         2.9.0.20241003
typing_extensions             4.12.2
tzdata                        2024.2
uri-template                  1.3.0
urllib3                       2.2.3
virtualenv                    20.27.0
wandb                         0.18.5
watchdog                      5.0.3
wcwidth                       0.2.13
webcolors                     24.8.0
webencodings                  0.5.1
websocket-client              1.8.0
websockets                    13.1
wheel                         0.44.0
widgetsnbextension            4.0.13
xtuner                        0.1.23         /mnt/workspace/jinbin_output/caption_v2/aurora/src/xtuner
xxhash                        3.5.0
yapf                          0.40.2
yarl                          1.16.0
yt-dlp                        2024.10.22
zipp                          3.20.2
zss                           1.2.0
zstandard                     0.23.0
```

My cuda version:
```bash
(aurora) root@dsw-2470-69f5b95b9c-d78s8:/mnt/workspace/jinbin_output/caption_v2/aurora# nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Feb__7_19:32:13_PST_2023
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0
```

**Comment by rese1f** [comment]
Hi we've never meet this issue before. but you can guess comment the line
`File "/mnt/workspace/jinbin_output/caption_v2/aurora/src/xtuner/xtuner/model/__init__.py", line 2, in <module>
    from .internvl import InternVL_V1_5`
it is not used for auroracap

**Comment by viiika** [comment]
Thanks for your answer. We comment the line 2 and line 3 related to InternVL_v1_5 and LLaVAModel then, but the issue still exists.

```bash
(aurora) root@dsw-2470-69f5b95b9c-d78s8:/mnt/workspace/jinbin_output/caption_v2/aurora# python inference.py     --model_path wchai/AuroraCap-7B-VID-xtuner     --prompt "Describe the video in detail."     --visual_input assets/auroracap/test.mp4     --num_frm 8     --token_kept_ratio 0.8     --temperature 0.0     --top_p 1.0     --num_beams 1     --max_new_tokens 2048
/root/anaconda3/envs/aurora/lib/python3.10/site-packages/_distutils_hack/__init__.py:54: UserWarning: Reliance on distutils from stdlib is deprecated. Users must rely on setuptools to provide the distutils module. Avoid importing distutils or import setuptools first, and avoid setting SETUPTOOLS_USE_DISTUTILS=stdlib. Register concerns at https://github.com/pypa/setuptools/issues/new?template=distutils-deprecation.yml
  warnings.warn(
[2024-10-25 02:44:14,671] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/mnt/workspace/jinbin_output/caption_v2/aurora/inference.py", line 9, in <module>
    from src.xtuner.xtuner.model.aurora import AuroraEncoder, AuroraModel
  File "/mnt/workspace/jinbin_output/caption_v2/aurora/src/xtuner/xtuner/model/__init__.py", line 4, in <module>
    from .aurora import AuroraModel
  File "/mnt/workspace/jinbin_output/caption_v2/aurora/src/xtuner/xtuner/model/aurora.py", line 13, in <module>
    from mmengine.model import BaseModel
  File "/root/anaconda3/envs/aurora/lib/python3.10/site-packages/mmengine/model/__init__.py", line 6, in <module>
    from .base_model import BaseDataPreprocessor, BaseModel, ImgDataPreprocessor
  File "/root/anaconda3/envs/aurora/lib/python3.10/site-packages/mmengine/model/base_model/__init__.py", line 2, in <module>
    from .base_model import BaseModel
  File "/root/anaconda3/envs/aurora/lib/python3.10/site-packages/mmengine/model/base_model/base_model.py", line 9, in <module>
    from mmengine.optim import OptimWrapper
  File "/root/anaconda3/envs/aurora/lib/python3.10/site-packages/mmengine/optim/__init__.py", line 2, in <module>
    from .optimizer import (OPTIM_WRAPPER_CONSTRUCTORS, OPTIMIZERS,
  File "/root/anaconda3/envs/aurora/lib/python3.10/site-packages/mmengine/optim/optimizer/__init__.py", line 5, in <module>
    from .builder import (OPTIM_WRAPPER_CONSTRUCTORS, OPTIMIZERS,
  File "/root/anaconda3/envs/aurora/lib/python3.10/site-packages/mmengine/optim/optimizer/builder.py", line 174, in <module>
    TRANSFORMERS_OPTIMIZERS = register_transformers_optimizers()
  File "/root/anaconda3/envs/aurora/lib/python3.10/site-packages/mmengine/optim/optimizer/builder.py", line 169, in register_transformers_optimizers
    OPTIMIZERS.register_module(name='Adafactor', module=Adafactor)
  File "/root/anaconda3/envs/aurora/lib/python3.10/site-packages/mmengine/registry/registry.py", line 661, in register_module
    self._register_module(module=module, module_name=name, force=force)
  File "/root/anaconda3/envs/aurora/lib/python3.10/site-packages/mmengine/registry/registry.py", line 611, in _register_module
    raise KeyError(f'{name} is already registered in {self.name} '
KeyError: 'Adafactor is already registered in optimizer at torch.optim'
```

**Comment by rese1f** [comment]
@viiika hi i try to reproduce your results, and i think the key is the torch version. seems like mmengine is not ready for torch 2.5, try 2.4 again ；)

**Comment by viiika** [comment]
Thanks for your reply. I downgraded torch from 2.5 to 2.4, but a new issue has arisen.

```bash
Traceback (most recent call last):
  File "/mnt/workspace/jinbin_output/caption_v2/aurora/inference.py", line 47, in <module>
    llm=AutoModelForCausalLM.from_pretrained(
  File "/root/anaconda3/envs/aurora/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 523, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/root/anaconda3/envs/aurora/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1162, in from_pretrained
    return config_class.from_dict(config_dict, **unused_kwargs)
  File "/root/anaconda3/envs/aurora/lib/python3.10/site-packages/transformers/configuration_utils.py", line 761, in from_dict
    config = cls(**config_dict)
  File "/root/anaconda3/envs/aurora/lib/python3.10/site-packages/transformers/models/llama/configuration_llama.py", line 160, in __init__
    self._rope_scaling_validation()
  File "/root/anaconda3/envs/aurora/lib/python3.10/site-packages/transformers/models/llama/configuration_llama.py", line 180, in _rope_scaling_validation
    raise ValueError(
ValueError: `rope_scaling` must be a dictionary with with two fields, `type` and `factor`, got {'factor': 4.0, 'rope_type': 'linear', 'type': 'linear'}
```

**Comment by rese1f** [comment]
Check this: https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct/discussions/15
You need to upgrade transformers by `pip install --upgrade transformers` :)
